apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-test
  namespace: testdeployment
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
         service:
            name: aks-test
            port:
              number: 80
